### ISSUE TITLE
Having issues running analyses

### ISSUE THREAD

**Issue by hamsamilton** [BackmanLab/PWSpy#22]
Hi,

When I run an analysis. I am seeing the following issue with the reflectance calculations.

INFO: 2023-09-21 20:30:17 pwspy_gui.PWSAnalysisApp._taskManagers.analysisManager.runSingle(109) - Using automatically detected camera corrections
INFO: 2023-09-21 20:30:17 pwspy_gui.PWSAnalysisApp._taskManagers.analysisManager.runSingle(116) - Initializing analysis
ERROR: 2023-09-21 20:30:22 pwspy_gui.PWSAnalysisApp._taskManagers.analysisManager.newFunc(50) - cannot reshape array of size 0 into shape (0,newaxis)
Traceback (most recent call last):
  File "/Users/samhamilton/miniconda3/envs/pwspyenv/lib/python3.11/site-packages/pwspy_gui/PWSAnalysisApp/_taskManagers/analysisManager.py", line 47, in newFunc
    func(*args)
  File "/Users/samhamilton/miniconda3/envs/pwspyenv/lib/python3.11/site-packages/pwspy_gui/PWSAnalysisApp/_taskManagers/analysisManager.py", line 117, in runSingle
    analysis = AnalysisClass(anSettings.getSaveableSettings(), anSettings.getExtraReflectanceMetadata(), ref)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samhamilton/miniconda3/envs/pwspyenv/lib/python3.11/site-packages/pwspy/analysis/pws.py", line 113, in __init__
    theoryR = reflectanceHelper.getReflectance(settings.referenceMaterial, Material.Glass, wavelengths=ref.wavelengths, NA=settings.numericalAperture)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samhamilton/miniconda3/envs/pwspyenv/lib/python3.11/site-packages/pwspy/utility/reflection/reflectanceHelper.py", line 157, in getReflectance
    d = s.calculateReflectance(np.array([0]))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samhamilton/miniconda3/envs/pwspyenv/lib/python3.11/site-packages/pwspy/utility/reflection/multilayerReflectanceEngine.py", line 363, in circularIntegration
    d = self.calculateReflectance(NAs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samhamilton/miniconda3/envs/pwspyenv/lib/python3.11/site-packages/pwspy/utility/reflection/multilayerReflectanceEngine.py", line 340, in calculateReflectance
    m = self._generateMatrix(polarization, NAs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samhamilton/miniconda3/envs/pwspyenv/lib/python3.11/site-packages/pwspy/utility/reflection/multilayerReflectanceEngine.py", line 313, in _generateMatrix
    matrices.append(self.propagationMatrix(el.getRefractiveIndex(self.wavelengths), el.d, NAs))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samhamilton/miniconda3/envs/pwspyenv/lib/python3.11/site-packages/pwspy/utility/reflection/multilayerReflectanceEngine.py", line 94, in getRefractiveIndex
    n = getRefractiveIndex(self.mat, wavelengths=wavelengths)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samhamilton/miniconda3/envs/pwspyenv/lib/python3.11/site-packages/pwspy/utility/reflection/reflectanceHelper.py", line 122, in getRefractiveIndex
    print("we are bug fixing this... the index is",
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samhamilton/miniconda3/envs/pwspyenv/lib/python3.11/site-packages/scipy/interpolate/_ndgriddata.py", line 266, in griddata
    ip = interp1d(points, values, kind=method, axis=0, bounds_error=False,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samhamilton/miniconda3/envs/pwspyenv/lib/python3.11/site-packages/scipy/interpolate/_interpolate.py", line 532, in __init__
    self._y = self._reshape_yi(self.y)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samhamilton/miniconda3/envs/pwspyenv/lib/python3.11/site-packages/scipy/interpolate/_polyint.py", line 112, in _reshape_yi
    return yi.reshape((yi.shape[0], -1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 0 into shape (0,newaxis)

~~~~~~

Do you know how to resolve this issue?

Of note, I am trying to run this software on Python 3.11 as Python 3.7 is incompatible with M1 Macs.

I also replaced np.float with float on line 72 of reflectanceHelper.py as np.float has depreciated.

Let me know what additional context I can provide. Thank you

**Comment by hamsamilton** [comment]
For whatever reason, the csv for the reflectance information for water was being read in an incorrect order.

The bandaid fix for this was to invert the first and last index within the reflectanceHelper.py code at line 88

88     df = df.loc[last:first]  # Crop to the first and last wavelengths that we have data for all materials.

**Comment by nanthony21** [comment]
My guess would be that you have a different version of [pandas](https://pandas.pydata.org/) than was used originally when writing this and something must have changed with indexing. If that is the case and this continues to be an issue the fix would be to more strictly limit the compatible versions of pandas by editing the Conda [meta.yaml]( https://github.com/BackmanLab/PWSpy/blob/master/conda.recipe/meta.yaml) file and then publishing a new version to Conda.

**Comment by hamsamilton** [comment]
That's my suspicion as well, although I haven't had time to root out precisely what caused the change on my installation.
